### ISSUE TITLE
Hide "Other" when there are no options left?

### ISSUE THREAD

**Issue by mehulkar** [eggboxio/quick-select#1]
Any way to leave out the "More" option?

Either by adding another option, or omitting the More option? I'm wrapping this in an ember addon and dynamically allowing users to pass in the number of values to break out with the option to break out ALL values.

**Comment by will-stone** [comment]
Hmm.. several ways I can do this, I'm thinking the most user-friendly solution would be to have the following option:

```
breakOutAll: false
```

If set to true, it overrides breakOutValues and breaks out all of the select options.

This shouldn't take me too long to add but if you'd like a temporary solution, you can hide it using CSS:

```
.quickselect__more { display: none; }
```

**Comment by will-stone** [comment]
Ok, this feature has now been added. Please see docs for example and info.

**Comment by mehulkar** [comment]
Wow, that was a quick turnaround. Thanks @eggboxio!  I will try it out on Monday!
