### ISSUE TITLE
Improve selection experience when using keyboard alone

### ISSUE THREAD

**Issue by ollicle** [eggboxio/quick-select#2]
Although the select element can still be focused with by keyboard tabbing alone, it is not visible, hampering keyboard interaction. Ensuring the select becomes visible upon focus may be the simplest solution to addressing the immediate accessibility issues.

It would be advantageous to permit the options revealed by this plugin to be focused using keyboard alone. To do so they must accept keyboard focus. I would consider rendering them as a set of labels (with associated radio buttons) to provide a good basis for this interaction without having to recreate all the expected behaviour from scratch (with spans).

**Comment by will-stone** [comment]
I'm not sure about adding more form elements, but this could presumably be easily solved with tabindex. I'll look into it shortly.

**Comment by will-stone** [comment]
Hmmm... tabindex allowed for highlighting the elements but not selecting them. I suppose the options here are to turn the breakout-items into form elements (as you suggested) then destroy them on submit, or listen for spacebar key presses. I like the idea of the latter and have found some info here: http://www.456bereastreet.com/archive/201302/making_elements_keyboard_focusable_and_clickable/
I'll look into incorporating those solutions.

**Comment by ollicle** [comment]
Considering there is already code to manage the selected state of the faux options, try replacing them with `<button type="button" aria-pressed="false">Value here</button>`. This will permit keyboard focus without providing an additional field value to the form submission.

The aria attribute is there to make the pressed state clear to screenreaders and the like. It ought to toggle between `true` and `false`. This value may also be used as a CSS hook to style the button differently for that state also.

```
[aria-pressed="true"].quickselect {
    background: #286090;
    color: #fff;
}
```

**Comment by will-stone** [comment]
Thanks Oliver. The reason I've been dancing around adding form elements, is that I (will be) using Quick[select] with a CakePHP project that has form security enabled; adding in form elements screws that up. I'm not sure about buttons, I suppose they would be ok with Cake. I'll give this a go later.

**Comment by will-stone** [comment]
Hi Oliver, this should now be keyboard compatible. I've changed the breakout spans to buttons, which allows for native browser keyboard interaction. Also I've added code in the plugin that listens for focus on the select box, and sets it to opacity=1 when focused. It all seems to work quite well so far: tested on IE11, Chrome and Firefox on Windows, and Chrome on Android. Please check for any regressions on your devices and let me know if it's broken.
Please let me know if you have any further feature/accessibility requests.

**Comment by ollicle** [comment]
Further enhancement may be possible with a deeper understanding than mine. This change big improvement! Good stuff.
