### ISSUE TITLE
Support disabled select boxes

### ISSUE THREAD

**Issue by emwee** [eggboxio/quick-select#3]
I want to incorporate this plugin in one of my projects but unfortunately it does not seem to handle disabled select boxes, e.g.:

```
<select disabled>
```

**Comment by will-stone** [comment]
What would be your expected result?

**Comment by emwee** [comment]
The buttons should be disabled and I'd want to be able to style disabled 'quickselect' elements. When I re-enable the original select element, the buttons should be automatically updated.

**Comment by will-stone** [comment]
Ok, so the created elements need to be listening for the disabled status of the select field. Hmmm... can't imagine that'll be too taxing but I'll take a look later.

**Comment by emwee** [comment]
Cool, thank you in advance!

**Comment by will-stone** [comment]
Hi @emwee, from the research I've been able to do, it doesn't look like listening for "disabled" change is possible without polling. Without adding too much bloat to the code, here's my proposed solution:
I've added in functionality that will add the disabled attribute to the break-out buttons and the select wrapper if the disabled attribute is detected on the select box on load. Please see the doc page for an added example showcasing this. As for updating the disabled status dynamically, I suggest you fire something like the following in your script when required:

```
$('.quickselect__btn, .quickselect__select').removeAttr("disabled");
```
