### ISSUE TITLE
chrome error

### ISSUE THREAD

**Issue by wilrevehl** [eggboxio/quick-select#6]
Hi Will, thanks for your nifty work. Curious if i'm alone in this - for some reason Chrome dev tools tells me Uncaught SyntaxError: Unexpected token . on your css file. I've inspected the file, there's not much to it. Seems okay. Any idea? Thanks!

**Comment by will-stone** [comment]
Hi, thanks. Nice to have a fan :) Hmmm... I don't see that on the demo page, is that where you're seeing it? If not, can you setup a JSFiddle that demonstrates it?

**Comment by wilrevehl** [comment]
Curiously, they don't appear on your demo site. But for some reason in my
use of your code for a WordPress site, there's that error. It's wild. I
don't see anything wrong with the file. My guess would be some sort of file
character type or something invisible.

**Comment by will-stone** [comment]
Ok, I'll take a look. Are you installing with bower? Are you using the the dist or src css file?

**Comment by wilrevehl** [comment]
Nope, just your files. I even tried replacing it with the one on your site
and it throws that error still. ​You can see it here:
http://mymedhousing.com/

**Comment by wilrevehl** [comment]
And thanks for taking a look, I really very much appreciate it.

**Comment by will-stone** [comment]
Found it. You're loading the css file as a script. Use link instead:
`<link rel="stylesheet" type="text/css" href="./.../quick-select/dist/css/quickselect.css">`
Let me know if you find any bugs or have any feature requests.

**Comment by wilrevehl** [comment]
Yeppers! A colleague of mine noticed that just a moment ago. Sorry for the
interruption. What a duh of the day. Thanks again.
