### ISSUE TITLE
More button appearance

### ISSUE THREAD

**Issue by gruz** [eggboxio/quick-select#8]
Hi. Just several screenshots to show the problem:

Here not nice:
http://quick-select.eggbox.io/
[<img src="http://static.xscreenshot.com/2016/08/18/16/screen_ba8e61a37f4f94d1c94809b5a781d872" width="200">](http://static.xscreenshot.com/2016/08/18/16/screen_ba8e61a37f4f94d1c94809b5a781d872)

Here older code, nicer

http://www.jqueryscript.net/demo/User-friendly-jQuery-Select-Box-Replacement-Quick-Select/
[<img src="http://static.xscreenshot.com/2016/08/18/16/screen_28eb1b919ed76ec3f25fee6685277fb3" width="200">](http://static.xscreenshot.com/2016/08/18/16/screen_28eb1b919ed76ec3f25fee6685277fb3)

Can be "solved" by removing this code

```
            // For keyboard navigation: show (opacity=1) original select box when focused
            $(el).focus(function(){
                $(this).css('opacity','1');
            }).blur(function() {
                $(this).css('opacity','0');
            });
```

But it's not a solution.

And I have no idea what to do.

**Comment by will-stone** [comment]
Indeed. This was added for accessibility reasons. If you don't reveal the original select menu on keyboard focus, a keyboard-only user may have trouble using the plugin. It isn't the prettiest solution I know but I feel it's an acceptable compromise to allow all users to access the plugin. I'll close this for now, but am happy to listen to suggestions.

**Comment by gruz** [comment]
Maybe we don't change the opacity on click, but only on keyboard in some way?

**Comment by will-stone** [comment]
I found this: http://stackoverflow.com/questions/5653332/differentiate-between-focus-event-triggered-by-keyboard-mouse but the best solution uses a timeout which would cause flicker. I'm never a fan of solutions involving setTimeout and try to avoid them if possible.

**Comment by gruz** [comment]
What is we leave the selectbox hidden, but on change focus replace the more text?

**Comment by will-stone** [comment]
It's not very consistent: if you tab through a page, the buttons get a blue outline (on Chrome on OSX, may be slightly different on your setup). If you remove the opacity trick: the selectbox focuses but the wrapper button doesn't get the outline. You could style it but then you're writing specific focus style for your setup. Try removing the code yourself (I've added dev instructions to the README) and seeing what I mean. It's a tricky one but I believe the current functionality works ok.
